name = "Window"
icon = "app-window"

[source]
type = "native"
kind = "window"
interval = 1

[badges.default]
template = "{{ title | truncate(length=40) | dim }}"
highlight = "{{ title | truncate(length=40) }}"
condition = "{{ title }}"

[[hooks]]
condition = '{{ changed(key="title") }}'
action = "show-badge:default"
timeout = 2
